title: Complete-Mastery-System
description: Complete Mastery System

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

search_enabled: true
toc_enabled: true
nav_sort: case_insensitive
heading_anchors: true

plugins:
  - jekyll-remote-theme
  
url: https://shivakrishnak.github.io/sk-pages

aux_links:
  Repository: https://github.com/shivakrishnak/sk-pages
